version: '3.2'

services:
    webserver:
        build:
            context: ./ccgui
            args:
                - database_host=database
                - database_port=5432
                - database_user_name=postgres
                - database_users_password=postgres
                - webserver_port=6251
                - shared_workspace_dir=/data

        ports:
            - "6251:6251"

        networks:
            - codecompass

        volumes:
            - type: volume
              source: parse_data
              target: /data

        stdin_open: true
        tty: true

    xercesparser:
        build:
            context: ./xerces
            args:
                - project_name=xerces
                - database_host=database
                - database_port=5432
                - database_user_name=postgres
                - database_users_password=postgres
                - project_workspace_dir=/mnt/ws
                - shared_workspace_dir=/data

        networks:
            - codecompass

        volumes:
            - type: volume
              source: parse_data
              target: /data

            - type: bind
              source: ./xercessrc
              target: /mnt/ws

    db:
        image: 'postgres:9.5'
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_INITDB_ARGS='-E "SQL_ASCII"'
        networks:
            codecompass:
                aliases:
                    - database

    dbadmin:
        image: 'quantumobject/docker-mywebsql'
        ports:
            - "8081:80"
        networks:
            - codecompass

networks:
  codecompass:

volumes:
  parse_data:
